### ISSUE TITLE
Allow to set http credentials

### ISSUE THREAD

**Issue by gdufrene** [magja/magja#101]
Hello,

on my environment,
for testing purpose, a copy of magento is deployed behind a HTTP password Authentication.

I'm not able to set proper credentials anywhere.

Object MagentoSoapClient is not really easy to extends (no propected fields, no default constructor), moreover, all service Impl require this object (why not only the Interface SoapClient ??)

At least, you should add some configuration in property file to set user and password used at HTTP level (set as credentials on httpClient).

Then, you should consider a small refactoring around MagentoSoapClient to ease its extensibility.

**Comment by zambrovski** [comment]
I'll take a look if we can change it fast.

**Comment by gdufrene** [comment]
I don't understand how this merge fix http authentication.
It adds support on proxy, and allow to authenticate on it, but it does not allow to authenticate on the targetted http server (magento host).

no ?

**Comment by zambrovski** [comment]
I see, so you are using HTTP Basic Authentication on Magento host?
Why are you doing this? 

Anyway, I have to look how to pass username and password to the connection factory.

**Comment by gdufrene** [comment]
Thanks for been so reactive :)

As said, two different environnement of magento deployed. 
One for "prod", open to public.
Another one for "testing", with Basic Auth.

**Comment by zambrovski** [comment]
Does it finally work? :-)
