### ISSUE TITLE
12 - create a common head comment for all classes 

### ISSUE THREAD

**Issue by ceefour** [magja/magja#12]
<pre>
Guys, I think we can create a common head comment for all classes,
something about licence and that things, look that example:
<a href="http://code.google.com/p/gwt-ext/source/browse/trunk/main/src/com/gwtext/client/animation/Easing.java" rel="nofollow">http://code.google.com/p/gwt-ext/source/browse/trunk/main/src/com/gwtext/client/animation/Easing.java</a>

How about?

</pre></br>Original link: http://code.google.com/p/magja/issues/detail?id=12

**Comment by zambrovski** [comment]
Housekeeping: stale issue closed.
