### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by nielsonjr** [magja/magja#124]
Hi, guys, I have some troubles with the maven dependency (1.1.0-SNAPSHOT) indicated in the README.md file. I tried to use it in my project, but it was not located. So, I found another dependency (1.0.3-SNAPSHOT), but it seems to be a previous version. Could you tell me which one is the correct dependency to use, please?

I want to use the 1.1.0-SNAPSHOT version in my project.

**Comment by zachma1989** [comment]
I have the same issue with the maven dependency. Any updates on this?

**Comment by zaferaltug** [comment]
I have the same issue, is it in another repository and where?

**Comment by haroldo-ok** [comment]
I'm having exactly the same problem. Is anyone even reading this?

**Comment by zambrovski** [comment]
I have to register the domain for sonatype to register it and make it public available. For now, you have to check it out and build yourself... sorry for that. I‘m on it but it is not ready yet....

**Comment by zambrovski** [comment]
Hi folks,

I just claimed the sonatype organization and will get access to it soon. Stay tuned, I'll publish the release as soon as I have the access to maven central.

Kind regards...

**Comment by zambrovski** [comment]
I just released 1.1.0 into maven central and updated the docs. It might last some time, until the artifact gets in there - but it is already in the staging repository of sonatype...
So - stay tuned, it will be available very soon.

**Comment by zambrovski** [comment]
magja 1.1.0 is available in maven central https://search.maven.org/#search%7Cga%7C1%7Cmagja
