### ISSUE TITLE
Product custom attributes - not able to set my custom attributes

### ISSUE THREAD

**Issue by gss0** [magja/magja#130]
Hi

we are using this wonderful project since few days.  

We encuntered a problem adding simple product with custom attributes.
This is the code:
` 
		
		ProductRemoteService xService = remoteServiceFactory.getProductRemoteService();
		
		String sku = "A0002";
		
		Product product = new Product();
		product.setSku(sku);
		product.setType(ProductType.SIMPLE);
		product.setName("Test product title");
		product.setPrice(123.51);
		product.setDescription("Descrizione intera");
		product.setEnabled(true);
		product.setWebsites(new Integer[] {1});
		
		List<Category> categorie = new ArrayList<Category>();
		Category c1 = new Category();
		c1.setId(21);		
		categorie.add(c1);
		product.setCategories(categorie);

		product.setQty(1.0);
		product.setInStock(true);
		product.setManageStock(true);
		
		byte[] data = MagjaFileUtils.getBytesFromFileURL("https://www.*****.com/***.jpg");

		Media image = new Media(); image.setName("Fronte"); image.setMime("image/jpeg"); image.setData(data);

		Set<Type> types = new HashSet<Type>(); types.add(Type.IMAGE); types.add(Type.SMALL_IMAGE); types.add(Type.THUMBNAIL);

		ProductMedia media = new ProductMedia(); media.setExclude(false); media.setImage(image); media.setLabel("Image A for Product"); media.setPosition(1); media.setTypes(types);

		product.addMedia(media);	
		product.setAttributeSet(new ProductAttributeSet(4, "Default")); 
		
		Map<String, Object> attributes = new HashMap<String, Object>();
		attributes.put("taglio", "1000");
		attributes.put("valuta", "Lire");
		attributes.put("conservazione", "FDS");		
		product.setAttributes(attributes);
		
		product.setMetaTitle("Meta title");
		product.setMetaKeyword("Meta keys");
		product.setMetaDescription("Meta Description");
		
		xService.add(product);
		System.out.println("DONE");`

The product was correctly added except all custom attributes.

Any solutions to solve this issue?

Thanks and best regards.

**Comment by gss0** [comment]
Solved.

My fault. All three field are "select" type. The 'value' of any of this attribute must be the OPTION_ID instead of value.

**Comment by zambrovski** [comment]
Sorry, I was too slow. Feel free to report any issues or experiences...

**Comment by gss0** [comment]
Thanks anyway!
