### ISSUE TITLE
Issue loading WSDL when using secure URL for host

### ISSUE THREAD

**Issue by davidplumridge** [magja/magja#72]
Using this host:

https://HOSTNAME/api/soap/

I get this error:

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://HOSTNAME/index.php/api/soap/index/?wsdl=1' : Start tag expected, '<' not found

I am using version 1.0.3-SNAPSHOT.

Does Magja support secure URL's?

**Comment by zambrovski** [comment]
Housekeeping: stale issue closed.
