### ISSUE TITLE
Cannot connect to Magento

### ISSUE THREAD

**Issue by sidwubf** [magja/magja#77]
Hi,
I'm using magja.
My code is:
            String username = "xxx";
            String password = "xxxx";
            String host = "xxxxx";
            SoapConfig soapConfig = new SoapConfig(username, password, host);
            MagentoSoapClient soapClient = MagentoSoapClient.getInstance(soapConfig);
            RemoteServiceFactory serviceFactory = new RemoteServiceFactory(soapClient);
            CustomerRemoteService remoteService = serviceFactory.getCustomerRemoteService();
            Customer customer = remoteService.getById(1);
            return customer.toString();

I'm pretty sure the username ,password and host are correct.
But i always got "Cannot connect to Magento".
I saw the source ,it says "prepare for Axis2 1.7+ / HttpClient 4.2+".
I used Axis2 1.7.0 and HttpClient 4.3.1.
So i need help.Tks.

**Comment by zambrovski** [comment]
What is your URL? 
It sould be http://<host>/index.php/api/soap/ if your magento is running in the root context.
