### ISSUE TITLE
setManageStock(true) has no effect

### ISSUE THREAD

**Issue by llidija** [magja/magja#88]
Hi,

I'm trying to set manage stock property to true and set product to "in stock" with some quantity. But manage stock is still being set to false and quantity is still 0.

My code:

```
product.setQty(new Double(20));
product.setInStock(true);
product.setManageStock(true);
```

I'm using magja-1.0.3-SNAPSHOT.

I didn't find any setManageStock() test. Can anyone please help with this issue or at least test it?

Thank you and kind regards,
Lidija

**Comment by zambrovski** [comment]
Hi,

have you tried the InventoryService instead of the ProductRemoteService?

**Comment by zambrovski** [comment]
This is definitely a bug, will fix it asap.

**Comment by llidija** [comment]
Hi,

I see this issue is closed so I'm sorry for my late response. 

This still didn't work for me. I had to modify ProductRemoteServiceImpl.updateInventory() - I added the else if block below:

  ```
...
    if (product.getInStock() == null && product.getQty() != null) {
      product.setInStock(product.getQty() > 0);
      properties.put("qty", product.getQty());
    }

    // ADDED
    else if (product.getInStock() != null && product.getQty() != null) {
      product.setInStock(product.getQty() > 0);
      properties.put("qty", product.getQty());
    }
    // end ADDED
...
``` 
Now the item is set to be in stock, the manageStock is set to true and the qty is saved correctly.

Kind regards,
Lidija

**Comment by zambrovski** [comment]
Hi Lidja,

I'm currently on vacation but will have a look on it soon.

Kind regards,

Simon

**Comment by zambrovski** [comment]
Do you think you could provide a Pull Request for this and a Unit Test and/or Integration Test ?
