### ISSUE TITLE
Remove System.out.print from Production code

### ISSUE THREAD

**Issue by fr33d00m** [magja/magja#89]
When writing any production code, especially a library such as this, the artefact owner should provide a means of controlling the log verbosity of said artefact.

Fortunately, most of the logging frameworks enable package based filtering, which only require the person to use any framework. While you are using a logging framework, there seem to be an awful lot of System.out.print statements about this project. I wonder why this is? Can't you just switch all of your system.out.print statements to log.info?

**Comment by ceefour** [comment]
Fixed by https://github.com/magja/magja/pull/90
